import { NavBar } from "@/components/NavBar";
import Head from "next/head";
import Link from "next/link";


export default function ResumePage() {
      return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-3xl h-screen bg-gradient-to-r from-dark-green to-35% to-medium-green">
        <header>
          <NavBar />
        </header>
        <div className="lg:ml-20 ml-10 lg:mt-10 w-full flex h-4/6 flex-col">
          <h1 className="lg:text-3xl text-natural-yellow font-semibold">
            Resume
          </h1>
          <div className="flex flex-row mt-10">
            <div className="basis-7/12 lg:text-lg lg:mr-20">
              <p className="mb-5">
                Nulla sit amet lectus mollis, luctus orci ac, sagittis neque.
                Donec sollicitudin augue nec viverra faucibus. Donec vel sodales
                odio. Quisque a turpis sit amet dolor consequat interdum et nec
                dui. Proin non tincidunt nunc. Proin et rutrum odio. Sed eget
                magna tincidunt nulla laoreet cursus. Maecenas tellus odio,
                tristique non felis ac, pharetra venenatis dui. Cras pretium,
                felis et bibendum tincidunt, mi velit accumsan dolor, vel
                porttitor nunc leo ut dolor.
              </p>
              <p>
                Duis lacus quam, lobortis at gravida vel, semper eget libero.
                Morbi luctus lectus vitae erat bibendum, in interdum est
                accumsan. Proin aliquam vulputate dapibus. Nam blandit, neque in
                consectetur facilisis, ipsum neque bibendum augue, eget semper
                nisi libero at ligula. Vestibulum maximus maximus risus eget
                consectetur. Morbi orci massa, eleifend nec felis sed, sodales
                luctus erat. Integer ut sagittis risus.
              </p>
              <div className="mt-10">
                <Link
                  href=""
                  className="border-2 border-natural-yellow py-2 px-6 rounded-full lg:text-lg text-sm animate-pulse hover:animate-none "
                >
                  <button>
                    Download PDF resume{" "}
                    <img src="pdf.png" className="h-6 inline-block mb-2"></img>
                  </button>
                </Link>
              </div>
            </div>
            <div className="basis-5/12">
              <p className="lg:text-lg lg:mb-5 text-natural-yellow font-semibold">
                Overview
              </p>
              <p className="lg:text-lg text-natural-yellow font-semibold">
                Name:{" "}
                <span className="text-white font-normal">
                  Alexander Iakovliuk
                </span>
              </p>
              <p className="lg:text-lg text-natural-yellow font-semibold">
                Age: <span className="text-white font-normal">32</span>
              </p>
              <p className="lg:text-lg text-natural-yellow font-semibold">
                Degree: <span className="text-white font-normal">PhD</span>
              </p>
              <p className="lg:text-lg text-natural-yellow font-semibold">
                Major:{" "}
                <span className="text-white font-normal">Roman languages</span>
              </p>
              <p className="lg:text-lg text-natural-yellow font-semibold">
                Experience:{" "}
                <span className="text-white font-normal">3.5 years</span>
              </p>
              <p className="lg:text-lg text-natural-yellow font-semibold">
                Hobbies:{" "}
                <span className="text-white font-normal">
                  Anything nerdy or learning new things
                </span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
